name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/app
            cd /home/ubuntu/app
            if [ ! -d ".git" ]; then
                git clone https://github.com/phanis-git/sample-devops-project1.git .
            else
               git pull origin main
            fi
            docker-compose down
            docker-compose up -d